version: '3.3'
services:
  elasticsearch-utils:
    container_name: elasticsearch-utils
    image: elasticsearch:7.8.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - "cluster.name=elasticsearch"
      - "discovery.type=single-node" #needed for 7.8.0
    logging:
      driver: none